title: Large Language Models' Interpretation and Trustworthiness (LLMIT)
description: Workshop at [CIKM 2023](https://uobevents.eventsair.com/cikm2023/)
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
